language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

install: brew install emscripten

before_script:
  - emcc
  - echo "LLVM_ROOT='/usr/local/opt/emscripten/libexec/llvm/bin'" >> ~/.emscripten

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
